MvcMusicStore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcMusicStore.Models;

namespace MvcMusicStore.Controllers {
    public class StoreController : Controller {
        MusicStoreEntities storeDB = new MusicStoreEntities();
        //
        // GET: /Store/

        public ActionResult Details() 
        {
            return View();
        }

        public ActionResult Browse() {
            return View();
        }

        public ActionResult Index() 
        {
            var genres = storeDB.Genres;
            return View(genres);
        }


        //
        // GET: /Store/GenreMenu

        [ChildActionOnly]
        public ActionResult GenreMenu()
        {
            var genres = storeDB.Genres.Take(9).ToList();

            return PartialView(genres);
        }

    }
}

MvcMusicStore/Views/Shared/_AlbumDetailsTemplatePartial.cshtml
<script id="album-details-template" type="text/x-kendo-template">
    <div class="album-details">
        <div class="image-container">
            <img src="" data-bind="attr: { src: data.AlbumArtUrl }" />
        </div>
        <div class="album-info-container">
            
            <div class="artist" data-bind="text: data.Artist.Name"></div>
            <div><span class="price" data-bind="textFormatted: data.Price" data-format="c"></span><span class="price-currency">USD</span></div>
            <div>X<input type="number" value="1" min="1" max="100" data-role="numerictextbox" data-decimals="0" data-format="n0" data-bind="value: quantity, events: { spin: updateQty }" /><span class="price-currency">qty</span></div>
            <div class="total" data-bind="textFormatted: total" data-format="c"></div>
            <a class="k-button" data-bind="click: addToCart">Add to Cart</a>
        </div>
    </div>
</script>

MvcMusicStore/Views/Shared/_AlbumListTemplatePartial.cshtml
<script id="album-template" type="text/x-kendo-template">
    <div class="album" data-bind="click: viewAlbumDetails">
        <img src="" data-bind="attr: { src: AlbumArtUrl }" />
        <span class="title" data-bind="text: Title"></span>
        <span class="artist" data-bind="text: Artist.Name"></span>
        <span class="price" data-bind="textFormatted: Price" data-format="c"></span>
    </div>
</script>

MvcMusicStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Kendo UI Music Store</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        <link href="~/Content/normalize.css" rel="stylesheet" />
        <link href="~/Content/themes/base/kendo.common.min.css" rel="stylesheet" />
        <link href="~/Content/themes/base/kendo.default.min.css" rel="stylesheet" />
        <link href="~/Content/themes/base/kendo.mobile.all.min.css" rel="stylesheet" />
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700' rel='stylesheet' type='text/css'>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
    </head>
    <body>
        <div id="wrapper">
        <header>
            <div class="container">
                <h1><a href="/">Awesome Sauce Music Store</a></h1>


                <section class="login-button">
                    @Html.Partial("_LoginPartial")
                </section>

                <nav>
                    <ul id="menu">
             
                        <li>Genres
                            <ul>
                                @{Html.RenderAction("GenreMenu", "Store");}
                            </ul>
                        </li>
                        <li>About
                            <ul>
                                <li>
                                    <div class="k-content menu-content">
                                        <img src="~/Images/kendo-logo.png" />
                                        <p>Try Kendo UI yourself in the interactive Kendo UI Dojo!</p>
                                        <p><a href="http://www.kendoui.com/dojo.aspx" target="_blank" class="k-button">Launch Kendo UI Dojo</a></p>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </nav>
           
                <section class="cart-search">
                    <input id="main-search"/>
                    <ul id="cart-menu"></ul>
                </section>
            </div>
        </header>

        <div id="body">
            @RenderBody()
        </div>
    </div>
        <footer>
            <section class="container">
                <ul>
                    <li><a href="http://www.telerik.com"><img src="/content/images/telerik-logo.png" alt="Telerik" /></a></li>
                    <li><a href="http://www.kendoui.com"><img src="/images/kendo-logo.png" alt="Kendo UI"/></a></li>
                </ul>
            </section>
        </footer>

        @Html.Partial("_AlbumDetailsTemplatePartial")
        @Html.Partial("_SearchResultTemplatePartial")

        <script src="~/Scripts/kendo.all.min.js"></script>
        @Scripts.Render("~/bundles/libs")
        @Scripts.Render("~/bundles/app")
        @RenderSection("scripts", required: false)
    </body>
</html>

MvcMusicStore/Views/Shared/_SearchResultTemplatePartial.cshtml
<script id="search-result-template" type="text/x-kendo-template">
    <div class="album-wide" data-album-id="${data.AlbumId}">
        <img src="${data.AlbumArtUrl}" />
        <div>
            <span>${data.Title}</span>
            <span>${data.Artist.Name}</span>
        </div>
    </div>
</script>